name: erickaufman
favicon: null
layout_spectrum: 0.4925
typography_spectrum: 0.48857
title: 'Eric Kaufman | Director'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9092a1'
    - '#5b5d69'
    - '#342640'
    - '#c9a19a'
  brandStrength: 0.0625
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
