name: Eric Kaufman
favicon: null
layout_spectrum: 0.75468
typography_spectrum: 0
title: 'Eric Kaufman | Director'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1c1c'
    - '#e5e5e5'
    - '#858585'
    - '#c1c1c1'
    - '#404040'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
