name: Eric Kaufman
favicon: null
layout_spectrum: 0
typography_spectrum: 0.99688
title: 'Eric Kaufman | Director'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030305'
    - '#3b1f14'
    - '#635950'
    - '#8b7d74'
    - '#a5a8b4'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
